# Generated by Django 5.0.6 on 2024-11-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashback',
            name='summasi',
            field=models.BigIntegerField(default=0, verbose_name='Cashback summa'),
        ),
    ]
