# Generated by Django 5.0.6 on 2024-11-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cashback_created_at_cashback_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, to='account.roles', verbose_name='Roles'),
        ),
    ]
