# Generated by Django 5.0.6 on 2024-11-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customuser_role_customuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashback',
            name='user_type',
            field=models.CharField(choices=[('1', "O'quvchi"), ('2', "O'qituvchi"), ('3', 'Direktor')], default=1, max_length=20, verbose_name='Foydalanuvchi turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashback',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Kirish'), ('2', "O'qituvchi"), ('3', "O'quvchi"), ('4', 'Admin')], max_length=20, null=True, verbose_name='Turi'),
        ),
    ]
