# Generated by Django 5.0.6 on 2024-11-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_cashback_user_type_alter_cashback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Referal tizim'), ('2', "Kurs uchun to'lov"), ('3', 'Admin')], max_length=20, null=True, verbose_name='Turi'),
        ),
    ]
