# Generated by Django 5.0.6 on 2024-12-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Belgisi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
        ),
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Viloyat')),
                ('tuman', models.CharField(blank=True, max_length=255, null=True, verbose_name='tuman')),
                ('maktab_raqami', models.BigIntegerField(blank=True, null=True, verbose_name='Maktab raqami')),
                ('sharntoma_raqam', models.BigIntegerField(blank=True, null=True, verbose_name='Sharntoma raqami')),
                ('nomi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinf_raqami', models.CharField(max_length=50, verbose_name='Sinf raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('belgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.belgisi', verbose_name='Belgisi')),
                ('maktab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinflar', to='school.maktab', verbose_name='Maktab')),
            ],
        ),
    ]
