# Generated by Django 5.0.6 on 2024-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maktab',
            name='nomi',
            field=models.CharField(default=1, max_length=255, verbose_name='Nomi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maktab',
            name='tuman',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tuman'),
        ),
        migrations.AlterField(
            model_name='maktab',
            name='viloyat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Viloyat'),
        ),
    ]
