# Generated by Django 5.0.6 on 2024-11-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_maktab_nomi_alter_maktab_tuman_alter_maktab_viloyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maktab',
            name='maktab_raqami',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Maktab raqami'),
        ),
        migrations.AlterField(
            model_name='maktab',
            name='nomi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='maktab',
            name='sharntoma_raqam',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Sharntoma raqami'),
        ),
    ]
