# Generated by Django 5.0.6 on 2024-12-11 12:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='E_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Hafta kunlarini tanlang', verbose_name='Dars kunlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Markaz nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlanganmi')),
                ('all_views', models.BooleanField(default=False, verbose_name="Barchaga ko'rinadi")),
                ('maktab', models.ManyToManyField(blank=True, related_name='centers', to='school.maktab', verbose_name='Maktablar')),
                ('rahbari', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rahbari')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Guruhga qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.e_groups', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
        ),
        migrations.AddField(
            model_name='e_groups',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', through='center.GroupMembership', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchilar"),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='center_images/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuv')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aloqa')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('image', models.ImageField(blank=True, null=True, upload_to='filial_images/', verbose_name='Bosh rasm')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqt")),
                ('admins', models.ManyToManyField(blank=True, related_name='administered_filials', to=settings.AUTH_USER_MODEL, verbose_name='Administratorlar')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.center', verbose_name="O'quv markazi")),
                ('images', models.ManyToManyField(blank=True, to='center.images', verbose_name="Qo'shimcha rasmlar")),
            ],
        ),
        migrations.CreateModel(
            name='Kasb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Kasb nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kasblar', to='center.center', verbose_name='Markaz')),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('narxi', models.BigIntegerField(verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='center.center', verbose_name='Markaz')),
            ],
        ),
        migrations.AddField(
            model_name='e_groups',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='center.kurs', verbose_name='Kurs'),
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='center.center', verbose_name='Markaz')),
                ('kasb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='center.kasb', verbose_name='Kasb')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('belgisi', models.CharField(max_length=100, verbose_name='Sinf Belgisi')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998 bilan boshlanishi va 9 raqamdan iborat bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqami')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('accept_group', 'Guruhga qabul qilindi'), ('rejected', 'Rad etilgan')], default='pending', max_length=15, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.filial', verbose_name='Filial')),
                ('kasb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.kasb', verbose_name='Kasb')),
                ('sinf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.sinf', verbose_name='Sinf')),
                ('yonalish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.yonalish', verbose_name="Yo'nalish")),
            ],
        ),
        migrations.AddField(
            model_name='kurs',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='center.yonalish', verbose_name="Yo'nalish"),
        ),
    ]
