# Generated by Django 5.0.6 on 2024-11-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('days_of_week', models.JSONField(default=list, help_text='Hafta kunlarini tanlang', verbose_name='Dars kunlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='center.kurs', verbose_name='Kurs')),
            ],
        ),
    ]
