# Generated by Django 5.0.6 on 2024-11-08 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_alter_e_groups_days_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Guruhga qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.e_groups', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
        ),
        migrations.AddField(
            model_name='e_groups',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', through='center.GroupMembership', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchilar"),
        ),
    ]
